"use server";

import { revalidatePath } from "next/cache";
import { createSupabaseServerClient } from "@/lib/supabase/server";

// ---------------------------------------------------------------------------
// Invite-link management, scoped to the logged-in couple. Like the content
// editor's actions, these run with the user's session so Row Level Security
// (supabase/schema.sql, invite_links_*_owner) guarantees a couple can only
// touch their own wedding's links — no service-role key.
// ---------------------------------------------------------------------------

export type InviteActionResult = { error?: string };

const NOT_CONFIGURED =
  "Supabase isn't configured. Add NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY to .env.local.";

const MAX_LABEL = 80;

// Resolve the current user's wedding id, or an error result.
async function ownerWeddingId() {
  const supabase = await createSupabaseServerClient();
  if (!supabase) return { error: NOT_CONFIGURED as string };

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: "Your session expired. Please log in again." };

  const { data: wedding } = await supabase
    .from("weddings")
    .select("id")
    .eq("owner_id", user.id)
    .order("created_at", { ascending: true })
    .limit(1)
    .maybeSingle();

  if (!wedding) return { error: "We couldn't find your wedding. Try again." };
  return { supabase, weddingId: wedding.id as string };
}

export async function createInviteLink(input: {
  label: string;
  kind: "group" | "personal";
  expectedCount?: number;
}): Promise<InviteActionResult> {
  const ctx = await ownerWeddingId();
  if ("error" in ctx) return { error: ctx.error };

  const label = input.label.trim().slice(0, MAX_LABEL);
  if (!label) return { error: "Give the link a name (e.g. “Dad’s friends”)." };

  const kind = input.kind === "personal" ? "personal" : "group";
  const expected_count =
    kind === "personal"
      ? Math.min(20, Math.max(1, Math.round(input.expectedCount || 1)))
      : 1;

  // token is generated by the DB default; RLS enforces the wedding is ours.
  const { error } = await ctx.supabase
    .from("invite_links")
    .insert({ wedding_id: ctx.weddingId, label, kind, expected_count });

  if (error) return { error: error.message };

  revalidatePath("/dashboard/invites");
  revalidatePath("/dashboard");
  return {};
}

export async function renameInviteLink(
  id: string,
  label: string
): Promise<InviteActionResult> {
  const ctx = await ownerWeddingId();
  if ("error" in ctx) return { error: ctx.error };

  const clean = label.trim().slice(0, MAX_LABEL);
  if (!clean) return { error: "The name can't be empty." };

  // RLS scopes the update to our own wedding's links.
  const { error } = await ctx.supabase
    .from("invite_links")
    .update({ label: clean })
    .eq("id", id);

  if (error) return { error: error.message };

  revalidatePath("/dashboard/invites");
  return {};
}

export async function deleteInviteLink(id: string): Promise<InviteActionResult> {
  const ctx = await ownerWeddingId();
  if ("error" in ctx) return { error: ctx.error };

  // Responses survive (rsvps.invite_link_id ON DELETE SET NULL → "Direct").
  const { error } = await ctx.supabase
    .from("invite_links")
    .delete()
    .eq("id", id);

  if (error) return { error: error.message };

  revalidatePath("/dashboard/invites");
  revalidatePath("/dashboard");
  return {};
}
